#lang info
(define collection "require-cl-cffi")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/require-cl-cffi.scrbl" ())))
(define pkg-desc "Require C FFI bindings from a common lisp file generated by cl-bindgen")
(define version "0.0")
(define license '(Apache-2.0 OR MIT))
